# Site settings
title: Maulana Kurniawan's Portfolio
description: A portfolio site about Maulana Kurniawan.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://maulana-kurniawan.github.io # the base hostname & protocol for your site e.g. https://maulana-kurniawan.github.io
banner: '/assets/img/banner/banner.png' # banner image location path for url preview in social media

# User settings
user_name: Maulana Kurniawan
user_title: Web Developer
email: maulana.kurniawan@outlook.co.id
linkedin:
github: maulana-kurniawan
gitlab:
facebook: maulana.kurn
instagram: maulana.kurn
threads:
twitter:
telegram: MaulanaKur
discord: 1340290306540834917
tiktok:

# Google-analytics
google-analytics:
  id: "" # Leave it blank if you don't want to use Google Analytics

collections:
  projects:
    output: false

sass:
  sass_dir: _sass
  sourcemap: never

plugins:
  - jekyll-seo-tag

exclude: ["Gemfile*", "LICENSE", "README.md"]
