# Site settings
title: Maulana Kurniawan's Portfolio
description: A portfolio site about Maulana Kurniawan.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://maulana-kurniawan.github.io # the base hostname & protocol for your site e.g. https://maulana-kurniawan.github.io

# User settings
user_name: Maulana Kurniawan
user_title: Junior Web Programmer
email: maulanakurniawan128@outlook.co.id
linkedin:
github: maulana-kurniawan
gitlab:
facebook: maulanakurnwn
instagram: maulanakurnwn
threads:
twitter:
telegram: maulanakurniawan_tg
discord:
tiktok:

# Google-analytics
google-analytics:
  id: "" # Leave it blank if you don't want to use Google Analytics

collections:
  projects:
    output: false

sass:
  sass_dir: _sass
  sourcemap: never

plugins:
  - jekyll-seo-tag

exclude: ["Gemfile*", "LICENSE", "README.md"]
